
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MYSLAVE_H
#define MYSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MySlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MySlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data MySlave_Data;
extern UNS32 app_counter;		/* Mapped at index 0x2000, subindex 0x00*/

#endif // MYSLAVE_H
